<?php

namespace Database\Seeders;

use App\Models\McuLab;
use App\Models\McuPackage;
use Illuminate\Database\Seeder;

class McuLabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // 1. Hematologi Lengkap
            [
                'code' => 'LAB-HEM-001',
                'name' => 'Hb',
                'category' => 'Hematologi Lengkap',
                'normal_value' => 'M (14.0-18.0) g/dL F (12.0-16.0) g/dL',
                'price' => 0,
                'display_order' => 1,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-002',
                'name' => 'Ht',
                'category' => 'Hematologi Lengkap',
                'normal_value' => 'M (42.0-52.0) % F (37.0-47.0) %',
                'price' => 0,
                'display_order' => 2,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-003',
                'name' => 'Eri',
                'category' => 'Hematologi Lengkap',
                'normal_value' => 'M (4.40-5.90) 10^6/uL F (3.80-5.20) 10^6/uL',
                'price' => 0,
                'display_order' => 3,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-004',
                'name' => 'Leuko',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(4.8-10.8) 10^3/uL',
                'price' => 0,
                'display_order' => 4,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-005',
                'name' => 'Trombo',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(150-450) 10^3/uL',
                'price' => 0,
                'display_order' => 5,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-006',
                'name' => 'LED',
                'category' => 'Hematologi Lengkap',
                'normal_value' => 'M (0-15) mm/jam F (0-20) mm/jam',
                'price' => 0,
                'display_order' => 6,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-007',
                'name' => 'MCV',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(79.0-99.0) fL',
                'price' => 0,
                'display_order' => 7,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-008',
                'name' => 'MCH',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(27.0-31.0) pg',
                'price' => 0,
                'display_order' => 8,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-009',
                'name' => 'MCHC',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(33.0-37.0) g/dL',
                'price' => 0,
                'display_order' => 9,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-010',
                'name' => 'Eos',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(2-4) %',
                'price' => 0,
                'display_order' => 10,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-011',
                'name' => 'Bas',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(0-1) %',
                'price' => 0,
                'display_order' => 11,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-012',
                'name' => 'Neut',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(50-70) %',
                'price' => 0,
                'display_order' => 12,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-013',
                'name' => 'N.Bat',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 13,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-014',
                'name' => 'Lim',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(25-40) %',
                'price' => 0,
                'display_order' => 14,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-015',
                'name' => 'Mon',
                'category' => 'Hematologi Lengkap',
                'normal_value' => '(2-8) %',
                'price' => 0,
                'display_order' => 15,
                'status' => true,
            ],
            [
                'code' => 'LAB-HEM-KES',
                'name' => 'Rekapitulasi Hematologi Lengkap',
                'category' => 'Hematologi Lengkap',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 16,
                'status' => true,
            ],

            // 2. Urine
            [
                'code' => 'LAB-URI-001',
                'name' => 'Warna',
                'category' => 'Urine',
                'normal_value' => 'Kuning',
                'price' => 0,
                'display_order' => 17,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-002',
                'name' => 'Kekeruhan',
                'category' => 'Urine',
                'normal_value' => 'Jernih',
                'price' => 0,
                'display_order' => 18,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-003',
                'name' => 'pH',
                'category' => 'Urine',
                'normal_value' => '4.5 - 8.0',
                'price' => 0,
                'display_order' => 19,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-004',
                'name' => 'B.Jenis',
                'category' => 'Urine',
                'normal_value' => '1.003 - 1.030',
                'price' => 0,
                'display_order' => 20,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-005',
                'name' => 'Protein',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 21,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-006',
                'name' => 'Glukosa',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 22,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-007',
                'name' => 'Bilirubin',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 23,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-008',
                'name' => 'Urobilinogen',
                'category' => 'Urine',
                'normal_value' => 'Normal',
                'price' => 0,
                'display_order' => 24,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-009',
                'name' => 'Nitrit',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 25,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-010',
                'name' => 'Keton',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 26,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-011',
                'name' => 'Darah',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 27,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-012',
                'name' => 'Leukosit',
                'category' => 'Urine',
                'normal_value' => 'Negatif',
                'price' => 0,
                'display_order' => 28,
                'status' => true,
            ],
            [
                'code' => 'LAB-URI-KES',
                'name' => 'Rekapitulasi Urine',
                'category' => 'Urine',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 29,
                'status' => true,
            ],

            // 3. Urine Sedimen
            [
                'code' => 'LAB-SED-001',
                'name' => 'Leukosit Sedimen',
                'category' => 'Urine Sedimen',
                'normal_value' => 'M (0.0 - 13.2) /uL F (0.0 - 16.9) /uL',
                'price' => 0,
                'display_order' => 30,
                'status' => true,
            ],
            [
                'code' => 'LAB-SED-002',
                'name' => 'Eritrosit Sedimen',
                'category' => 'Urine Sedimen',
                'normal_value' => 'M (0.0 - 13.6) /uL F (0.0 - 22.7) /uL',
                'price' => 0,
                'display_order' => 31,
                'status' => true,
            ],
            [
                'code' => 'LAB-SED-003',
                'name' => 'Epitel',
                'category' => 'Urine Sedimen',
                'normal_value' => 'M (0.0 - 5.2) /uL F (0.0 - 39.6) /uL',
                'price' => 0,
                'display_order' => 32,
                'status' => true,
            ],
            [
                'code' => 'LAB-SED-004',
                'name' => 'Kristal',
                'category' => 'Urine Sedimen',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 33,
                'status' => true,
            ],
            [
                'code' => 'LAB-SED-005',
                'name' => 'Silinder',
                'category' => 'Urine Sedimen',
                'normal_value' => 'M (0.00 - 0.40) /uL F (0.00 - 0.56) /uL',
                'price' => 0,
                'display_order' => 34,
                'status' => true,
            ],
            [
                'code' => 'LAB-SED-006',
                'name' => 'Bakteri',
                'category' => 'Urine Sedimen',
                'normal_value' => 'M (0.0 - 26.4) /uL F (0.0 - 130.7) /uL',
                'price' => 0,
                'display_order' => 35,
                'status' => true,
            ],
            [
                'code' => 'LAB-SED-KES',
                'name' => 'Rekapitulasi Urine Sedimen',
                'category' => 'Urine Sedimen',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 36,
                'status' => true,
            ],

            // 4. Fungsi Liver
            [
                'code' => 'LAB-LIV-001',
                'name' => 'SGOT',
                'category' => 'Fungsi Liver',
                'normal_value' => 'M (<=50) U/L F (<=35) U/L',
                'price' => 0,
                'display_order' => 37,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIV-002',
                'name' => 'SGPT',
                'category' => 'Fungsi Liver',
                'normal_value' => 'M (<=50) U/L F (<=35) U/L',
                'price' => 0,
                'display_order' => 38,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIV-003',
                'name' => 'ALP',
                'category' => 'Fungsi Liver',
                'normal_value' => '40 - 129 U/L',
                'price' => 0,
                'display_order' => 39,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIV-004',
                'name' => 'GAMMA',
                'category' => 'Fungsi Liver',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 40,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIV-KES',
                'name' => 'Rekapitulasi Fungsi Liver',
                'category' => 'Fungsi Liver',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 41,
                'status' => true,
            ],

            // 5. Lipid Profil
            [
                'code' => 'LAB-LIP-001',
                'name' => 'Chol.Total',
                'category' => 'Lipid Profil',
                'normal_value' => '< 200 mg/dL',
                'price' => 0,
                'display_order' => 42,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIP-002',
                'name' => 'Trigliseride',
                'category' => 'Lipid Profil',
                'normal_value' => 'Optimal : <150 mg/dL Borderline high : 150 - 199 mg/dL High : 200 - 499 mg/dL Very high : >500',
                'price' => 0,
                'display_order' => 43,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIP-003',
                'name' => 'LDL',
                'category' => 'Lipid Profil',
                'normal_value' => 'Low risk : < 130 mg/dL Moderate risk : 130 - 159 mg/dL High risk : > 160 mg/dL',
                'price' => 0,
                'display_order' => 44,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIP-004',
                'name' => 'HDL',
                'category' => 'Lipid Profil',
                'normal_value' => 'M (35 - 55) mg/dL F (45 - 65) mg/dL',
                'price' => 0,
                'display_order' => 45,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIP-005',
                'name' => 'CVD Rasio',
                'category' => 'Lipid Profil',
                'normal_value' => 'NAN',
                'price' => 0,
                'display_order' => 46,
                'status' => true,
            ],
            [
                'code' => 'LAB-LIP-KES',
                'name' => 'Rekapitulasi Lipid Profil',
                'category' => 'Lipid Profil',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 47,
                'status' => true,
            ],

            // 6. Fungsi Ginjal
            [
                'code' => 'LAB-GIN-001',
                'name' => 'Ureum',
                'category' => 'Fungsi Ginjal',
                'normal_value' => '< 50 mg/dL',
                'price' => 0,
                'display_order' => 48,
                'status' => true,
            ],
            [
                'code' => 'LAB-GIN-002',
                'name' => 'Kreatinin',
                'category' => 'Fungsi Ginjal',
                'normal_value' => 'M (0.67 - 1.17) mg/dL F (0.51 - 0.95) mg/dL',
                'price' => 0,
                'display_order' => 49,
                'status' => true,
            ],
            [
                'code' => 'LAB-GIN-003',
                'name' => 'eGFR',
                'category' => 'Fungsi Ginjal',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 50,
                'status' => true,
            ],
            [
                'code' => 'LAB-GIN-004',
                'name' => 'Asam Urat',
                'category' => 'Fungsi Ginjal',
                'normal_value' => 'M (3.4 - 7.0) mg/dL F (2.4 - 5.7) mg/dL',
                'price' => 0,
                'display_order' => 51,
                'status' => true,
            ],
            [
                'code' => 'LAB-GIN-KES',
                'name' => 'Rekapitulasi Fungsi Ginjal',
                'category' => 'Fungsi Ginjal',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 52,
                'status' => true,
            ],

            // 7. Glukosa Darah
            [
                'code' => 'LAB-GLU-001',
                'name' => 'Puasa',
                'category' => 'Glukosa Darah',
                'normal_value' => '(70-115) mg/dL',
                'price' => 0,
                'display_order' => 53,
                'status' => true,
            ],
            [
                'code' => 'LAB-GLU-002',
                'name' => '2 JPP',
                'category' => 'Glukosa Darah',
                'normal_value' => '<140 mg/dL',
                'price' => 0,
                'display_order' => 54,
                'status' => true,
            ],
            [
                'code' => 'LAB-GLU-003',
                'name' => 'HbA1c',
                'category' => 'Glukosa Darah',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 55,
                'status' => true,
            ],
            [
                'code' => 'LAB-GLU-KES',
                'name' => 'Rekapitulasi Glukosa Darah',
                'category' => 'Glukosa Darah',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 56,
                'status' => true,
            ],

            // 8. Imunologi
            [
                'code' => 'LAB-IMU-001',
                'name' => 'HbsAg',
                'category' => 'Imunologi',
                'normal_value' => 'Non Reaktif',
                'price' => 0,
                'display_order' => 57,
                'status' => true,
            ],
            [
                'code' => 'LAB-IMU-002',
                'name' => 'Anti Hbs',
                'category' => 'Imunologi',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 58,
                'status' => true,
            ],
            [
                'code' => 'LAB-IMU-003',
                'name' => 'PSA Total',
                'category' => 'Imunologi',
                'normal_value' => '< 4.0 ng/mL',
                'price' => 0,
                'display_order' => 59,
                'status' => true,
            ],
            [
                'code' => 'LAB-IMU-004',
                'name' => 'Tumor Marker CEA',
                'category' => 'Imunologi',
                'normal_value' => '0-2.5 ng/mL',
                'price' => 0,
                'display_order' => 60,
                'status' => true,
            ],
            [
                'code' => 'LAB-IMU-KES',
                'name' => 'Rekapitulasi Imunologi',
                'category' => 'Imunologi',
                'normal_value' => 'Dalam Batas Normal',
                'price' => 0,
                'display_order' => 61,
                'status' => true,
            ],

            // 9. Lainnya
            [
                'code' => 'LAB-LAI-001',
                'name' => 'Lainnya',
                'category' => 'Lainnya',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 62,
                'status' => true,
            ],
            [
                'code' => 'LAB-LAI-KES',
                'name' => 'Rekapitulasi Lainnya',
                'category' => 'Lainnya',
                'normal_value' => '-',
                'price' => 0,
                'display_order' => 63,
                'status' => true,
            ],
        ];

        $labIds = [];
        foreach ($items as $item) {
            $created = McuLab::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
            $labIds[] = $created->id;
        }

        // Automatically assign all seeded laboratory exams to all active packages
        $packages = McuPackage::where('status', true)->get();
        foreach ($packages as $package) {
            foreach ($labIds as $labId) {
                $package->items()->firstOrCreate([
                    'item_type' => McuLab::class,
                    'item_id' => $labId
                ]);
            }
        }
    }
}
